# Generated by Django 5.2.13 on 2026-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppilot_app', '0005_crop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='suitable_soil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
