# Generated by Django 5.2.13 on 2026-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppilot_app', '0006_alter_crop_season_alter_crop_suitable_soil'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
