# Generated by Django 5.2.13 on 2026-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('croppilot_app', '0007_crop_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile',
            field=models.ImageField(default='farmer_pic/default.jpg', upload_to='farmer_pic'),
        ),
    ]
